CREATE VOLATILE TABLE VT_CAMPANHA AS
(
    SELECT
        NUMERO_BENEFICIO,
        CAMPANHA
    FROM
    (
        SELECT
            NUMERO_BENEFICIO,
            CAMPANHA,
            ROW_NUMBER() OVER
            (
                PARTITION BY NUMERO_BENEFICIO
                ORDER BY CAMPANHA
            ) AS RN
        FROM BASE_EXEMPLO_02.TABELA_EXEMPLO_020
    ) X
    WHERE RN = 1
) WITH DATA
PRIMARY INDEX (NUMERO_BENEFICIO)
ON COMMIT PRESERVE ROWS
;

CREATE VOLATILE TABLE VT_BEN_CAD AS
(
    SELECT DISTINCT
        'BENEFICIARIO_CADUNICO' AS TIPO_REGISTRO,
        A.NU_NB,
        B_BEN.CO_FAMILIAR_FAM,
        A.NU_CPF_T,
        B_BEN.NUM_CPF_PESSOA,
        B_BEN.CO_CHV_NATURAL_PESSOA,
        A.ID_NIT_T AS NU_NIS_T,
        B_BEN.NUM_NIS_PESSOA_ATUAL,
        A.NM_TIT_BENEF_T,
        B_BEN.NOM_PESSOA,
        CASE B_BEN.COD_PARENTESCO_RF_PESSOA
            WHEN 1  THEN 'Pessoa Responsável pela Unidade Familiar - RF'
            WHEN 2  THEN 'Cônjuge ou companheiro(a)'
            WHEN 3  THEN 'Filho(a)'
            WHEN 4  THEN 'Enteado(a)'
            WHEN 5  THEN 'Neto(a) ou bisneto(a)'
            WHEN 6  THEN 'Pai ou mãe'
            WHEN 7  THEN 'Sogro(a)'
            WHEN 8  THEN 'Irmão ou irmã'
            WHEN 9  THEN 'Genro ou nora'
            WHEN 10 THEN 'Outro parente'
            WHEN 11 THEN 'Não parente'
            ELSE 'Código não mapeado'
        END AS DESC_PARENTESCO,
        '1' AS FLAG_CADUNICO,
        CASE
            WHEN M_ANT.NU_NB IS NOT NULL THEN '1' ELSE '0'
        END AS FLAG_REF_MACICA_ANTERIOR,
        A.NM_UF_MUN_T AS UF_MACICA,
        A.NM_MUN_T AS MUNICIPIO_MACICA,
        C.NO_SG_UF AS UF_CAD,
        C.NO_MUNICIPIO AS MUNICIPIO_CAD,
        B_BEN.SG_UF_APP AS UF_AG_PGD,
        B_BEN.NO_MUNICIPIO_APP AS MUNICIPIO_AG_PGD,
        A.DT_NASC_T,
        B_BEN.DTA_NASC_PESSOA,
        CAST
        (
            MONTHS_BETWEEN
            (
                LAST_DAY(CAST(CAST(A.NU_MES_REF AS CHAR(6)) || '01' AS DATE FORMAT 'YYYYMMDD')),
                A.DT_NASC_T
            ) / 12 AS INTEGER
        ) AS IDADE_T,
        CAST
        (
            MONTHS_BETWEEN
            (
                LAST_DAY(CAST(CAST(A.NU_MES_REF AS CHAR(6)) || '01' AS DATE FORMAT 'YYYYMMDD')),
                B_BEN.DTA_NASC_PESSOA
            ) / 12 AS INTEGER
        ) AS IDADE_PESSOA,
        A.NM_MAE_T,
        B_BEN.NOM_COMPLETO_MAE_PESSOA,
        CASE 
            WHEN A.CS_SEXO_T = 1 THEN 'MASCULINO'
            WHEN A.CS_SEXO_T = 3 THEN 'FEMININO'
            WHEN B_BEN.COD_SEXO_PESSOA = 1 THEN 'MASCULINO'
            WHEN B_BEN.COD_SEXO_PESSOA = 2 THEN 'FEMININO'
            ELSE 'NAO INFORMADO'
        END AS GENERO,
        CASE
            WHEN B_BEN.COD_RACA_COR_PESSOA = 1 THEN 'BRANCA'
            WHEN B_BEN.COD_RACA_COR_PESSOA = 2 THEN 'PRETA'
            WHEN B_BEN.COD_RACA_COR_PESSOA = 3 THEN 'AMARELA'
            WHEN B_BEN.COD_RACA_COR_PESSOA = 4 THEN 'PARDA'
            WHEN B_BEN.COD_RACA_COR_PESSOA = 5 THEN 'INDIGENA'
            ELSE 'NAO INFORMADO'
        END AS RACA_COR,
        B_BEN.IND_DORMIR_RUA_MEMB,
        CASE
            WHEN B_BEN.COD_FAMILIA_INDIGENA_FAM = 1 THEN '1'
            WHEN B_BEN.COD_FAMILIA_INDIGENA_FAM = 2 THEN '0'
        END AS FAMILIA_INDIGENA,
        CASE
            WHEN B_BEN.IND_FAMILIA_QUILOMBOLA_FAM = 1 THEN '1'
            WHEN B_BEN.IND_FAMILIA_QUILOMBOLA_FAM = 2 THEN '0'
        END AS FAMILIA_QUILOMBOLA,
        A.CS_ESPECIE,
        A.CS_DIAG_1 AS CID,
        CASE 
            WHEN D.DS_DESCRICAO IS NOT NULL THEN D.DS_DESCRICAO
            WHEN D.DS_DESCRICAO IS NULL AND A.CS_ESPECIE <> 87 THEN 'NAO SE APLICA'
            ELSE 'NAO ENCONTRADO'
        END AS DESCRICAO_CID,
        CASE 
            WHEN A.CS_DESPACHO <> 4 THEN 'ADMINISTRATIVA'
            WHEN A.CS_DESPACHO = 4 THEN 'JUDICIAL'
        END AS TIPO_DESPACHO,
        A.D2_DDB AS DT_DESPACHO,
        A.D2_DER AS DT_ENTRADA_REQUERIMENTO,
        A.D2_DIB AS DT_INICIO_BENEFICIO,
        CASE    
            WHEN CAST(E.DT_ATUALIZACAO_FAM AS DATE) BETWEEN DT_EXTRACAO_DADOS_HDR - INTERVAL '2' YEAR AND DT_EXTRACAO_DADOS_HDR
                 THEN 'ATUALIZADO'
            ELSE 'DESATUALIZADO'
        END AS SITUACAO_CAD_UNICO,
        CASE 
            WHEN F.CAMPANHA IS NOT NULL THEN F.CAMPANHA
            ELSE 'NAO'
        END AS PARTICIPACAO_CAMPANHA,
        B_BEN.DTA_ATUAL_MEMB,
        A.NU_MES_REF
    FROM BASE_EXEMPLO_05.TABELA_EXEMPLO_072, ---------------------------referencia posterior
         BASE_EXEMPLO_06.TABELA_EXEMPLO_073 A
    JOIN
    (
        SELECT DISTINCT
            CO_NB,
            CO_FAMILIAR_FAM,
            NUM_CPF_PESSOA,
            CO_CHV_NATURAL_PESSOA,
            NUM_NIS_PESSOA_ATUAL,
            NOM_PESSOA,
            COD_PARENTESCO_RF_PESSOA,
            SG_UF_APP,
            NO_MUNICIPIO_APP,
            DTA_NASC_PESSOA,
            NOM_COMPLETO_MAE_PESSOA,
            COD_SEXO_PESSOA,
            COD_RACA_COR_PESSOA,
            IND_DORMIR_RUA_MEMB,
            COD_FAMILIA_INDIGENA_FAM,
            IND_FAMILIA_QUILOMBOLA_FAM,
            DTA_ATUAL_MEMB,
            CO_MUNIC_IBGE_2_FAM,
            CO_MUNIC_IBGE_5_FAM,
            NU_MES_REF_MACICA
        FROM BASE_EXEMPLO_07.TABELA_EXEMPLO_079 ---------------------------referencia batimento
        WHERE NU_MES_REF_MACICA = 202507 ---------------------------referencia
          AND CO_NB IS NOT NULL
    ) B_BEN
        ON A.NU_NB = B_BEN.CO_NB
       AND A.NU_MES_REF = B_BEN.NU_MES_REF_MACICA
    LEFT JOIN
    (
        SELECT DISTINCT
            NU_NB
        FROM BASE_EXEMPLO_06.TABELA_EXEMPLO_073
        WHERE CS_SIT_BENEF = 0
          AND CS_ESPECIE IN (11,12,18,30,40,60,87,88)
          AND CS_PA <> 3
          AND NU_MES_REF = 202506 ---------------------------referencia anterior
    ) M_ANT
        ON A.NU_NB = M_ANT.NU_NB
    LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_068 C
        ON TRIM
           (
               CAST(B_BEN.CO_MUNIC_IBGE_2_FAM AS CHAR(2)) ||
               LPAD(CAST(B_BEN.CO_MUNIC_IBGE_5_FAM AS VARCHAR(5)), 5, '0')
           ) = C.CO_IBGE7
    LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_069 D
        ON A.CS_DIAG_1 = D.CO_CID
    LEFT JOIN BASE_EXEMPLO_05.TABELA_EXEMPLO_071 E ---------------------------referencia posterior
        ON B_BEN.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
    LEFT JOIN VT_CAMPANHA F
        ON A.NU_NB = F.NUMERO_BENEFICIO
    WHERE A.CS_SIT_BENEF = 0
      AND A.CS_ESPECIE IN (11,12,18,30,40,60,87,88)
      AND A.CS_PA <> 3
      AND A.NU_MES_REF = 202507 ---------------------------referencia
) WITH DATA
PRIMARY INDEX (CO_FAMILIAR_FAM)
ON COMMIT PRESERVE ROWS
;



INSERT INTO BASE_EXEMPLO_01.TABELA_EXEMPLO_002
(
    TIPO_REGISTRO,
    NU_NB,
    CO_FAMILIAR_FAM,
    NU_CPF_T,
    NUM_CPF_PESSOA,
    CO_CHV_NATURAL_PESSOA,
    NU_NIS_T,
    NUM_NIS_PESSOA_ATUAL,
    NM_TIT_BENEF_T,
    NOM_PESSOA,
    DESC_PARENTESCO,
    FLAG_CADUNICO,
    FLAG_REF_MACICA_ANTERIOR,
    UF_MACICA,
    MUNICIPIO_MACICA,
    UF_CAD,
    MUNICIPIO_CAD,
    UF_AG_PGD,
    MUNICIPIO_AG_PGD,
    DT_NASC_T,
    DTA_NASC_PESSOA,
    IDADE_T,
    IDADE_PESSOA,
    NM_MAE_T,
    NOM_COMPLETO_MAE_PESSOA,
    GENERO,
    RACA_COR,
    IND_DORMIR_RUA_MEMB,
    FAMILIA_INDIGENA,
    FAMILIA_QUILOMBOLA,
    CS_ESPECIE,
    CID,
    DESCRICAO_CID,
    TIPO_DESPACHO,
    DT_DESPACHO,
    DT_ENTRADA_REQUERIMENTO,
    DT_INICIO_BENEFICIO,
    SITUACAO_CAD_UNICO,
    PARTICIPACAO_CAMPANHA,
    DTA_ATUAL_MEMB,
    NU_MES_REF
)
SELECT
    TIPO_REGISTRO,
    NU_NB,
    CO_FAMILIAR_FAM,
    NU_CPF_T,
    NUM_CPF_PESSOA,
    CO_CHV_NATURAL_PESSOA,
    NU_NIS_T,
    NUM_NIS_PESSOA_ATUAL,
    NM_TIT_BENEF_T,
    NOM_PESSOA,
    DESC_PARENTESCO,
    FLAG_CADUNICO,
    FLAG_REF_MACICA_ANTERIOR,
    UF_MACICA,
    MUNICIPIO_MACICA,
    UF_CAD,
    MUNICIPIO_CAD,
    UF_AG_PGD,
    MUNICIPIO_AG_PGD,
    DT_NASC_T,
    DTA_NASC_PESSOA,
    IDADE_T,
    IDADE_PESSOA,
    NM_MAE_T,
    NOM_COMPLETO_MAE_PESSOA,
    GENERO,
    RACA_COR,
    IND_DORMIR_RUA_MEMB,
    FAMILIA_INDIGENA,
    FAMILIA_QUILOMBOLA,
    CS_ESPECIE,
    CID,
    DESCRICAO_CID,
    TIPO_DESPACHO,
    DT_DESPACHO,
    DT_ENTRADA_REQUERIMENTO,
    DT_INICIO_BENEFICIO,
    SITUACAO_CAD_UNICO,
    PARTICIPACAO_CAMPANHA,
    DTA_ATUAL_MEMB,
    NU_MES_REF
FROM VT_BEN_CAD
;

INSERT INTO BASE_EXEMPLO_01.TABELA_EXEMPLO_002
(
    TIPO_REGISTRO,
    NU_NB,
    CO_FAMILIAR_FAM,
    NU_CPF_T,
    NUM_CPF_PESSOA,
    CO_CHV_NATURAL_PESSOA,
    NU_NIS_T,
    NUM_NIS_PESSOA_ATUAL,
    NM_TIT_BENEF_T,
    NOM_PESSOA,
    DESC_PARENTESCO,
    FLAG_CADUNICO,
    FLAG_REF_MACICA_ANTERIOR,
    UF_MACICA,
    MUNICIPIO_MACICA,
    UF_CAD,
    MUNICIPIO_CAD,
    UF_AG_PGD,
    MUNICIPIO_AG_PGD,
    DT_NASC_T,
    DTA_NASC_PESSOA,
    IDADE_T,
    IDADE_PESSOA,
    NM_MAE_T,
    NOM_COMPLETO_MAE_PESSOA,
    GENERO,
    RACA_COR,
    IND_DORMIR_RUA_MEMB,
    FAMILIA_INDIGENA,
    FAMILIA_QUILOMBOLA,
    CS_ESPECIE,
    CID,
    DESCRICAO_CID,
    TIPO_DESPACHO,
    DT_DESPACHO,
    DT_ENTRADA_REQUERIMENTO,
    DT_INICIO_BENEFICIO,
    SITUACAO_CAD_UNICO,
    PARTICIPACAO_CAMPANHA,
    DTA_ATUAL_MEMB,
    NU_MES_REF
)
SELECT DISTINCT
    'MEMBRO_FAMILIAR' AS TIPO_REGISTRO,
    NULL AS NU_NB,
    FAM.CO_FAMILIAR_FAM,
    NULL AS NU_CPF_T,
    FAM.NUM_CPF_PESSOA,
    FAM.CO_CHV_NATURAL_PESSOA,
    NULL AS NU_NIS_T,
    FAM.NUM_NIS_PESSOA_ATUAL,
    NULL AS NM_TIT_BENEF_T,
    FAM.NOM_PESSOA,
    CASE FAM.COD_PARENTESCO_RF_PESSOA
        WHEN 1  THEN 'Pessoa Responsável pela Unidade Familiar - RF'
        WHEN 2  THEN 'Cônjuge ou companheiro(a)'
        WHEN 3  THEN 'Filho(a)'
        WHEN 4  THEN 'Enteado(a)'
        WHEN 5  THEN 'Neto(a) ou bisneto(a)'
        WHEN 6  THEN 'Pai ou mãe'
        WHEN 7  THEN 'Sogro(a)'
        WHEN 8  THEN 'Irmão ou irmã'
        WHEN 9  THEN 'Genro ou nora'
        WHEN 10 THEN 'Outro parente'
        WHEN 11 THEN 'Não parente'
        ELSE 'Código não mapeado'
    END AS DESC_PARENTESCO,
    '1' AS FLAG_CADUNICO,
    B.FLAG_REF_MACICA_ANTERIOR,
    NULL AS UF_MACICA,
    NULL AS MUNICIPIO_MACICA,
    C.NO_SG_UF AS UF_CAD,
    C.NO_MUNICIPIO AS MUNICIPIO_CAD,
    FAM.SG_UF_APP AS UF_AG_PGD,
    FAM.NO_MUNICIPIO_APP AS MUNICIPIO_AG_PGD,
    NULL AS DT_NASC_T,
    FAM.DTA_NASC_PESSOA,
    NULL AS IDADE_T,
    CAST
    (
        MONTHS_BETWEEN
        (
            LAST_DAY(CAST(CAST(B.NU_MES_REF AS CHAR(6)) || '01' AS DATE FORMAT 'YYYYMMDD')),
            FAM.DTA_NASC_PESSOA
        ) / 12 AS INTEGER
    ) AS IDADE_PESSOA,
    NULL AS NM_MAE_T,
    FAM.NOM_COMPLETO_MAE_PESSOA,
    CASE
        WHEN FAM.COD_SEXO_PESSOA = 1 THEN 'MASCULINO'
        WHEN FAM.COD_SEXO_PESSOA = 2 THEN 'FEMININO'
        ELSE 'NAO INFORMADO'
    END AS GENERO,
    CASE
        WHEN FAM.COD_RACA_COR_PESSOA = 1 THEN 'BRANCA'
        WHEN FAM.COD_RACA_COR_PESSOA = 2 THEN 'PRETA'
        WHEN FAM.COD_RACA_COR_PESSOA = 3 THEN 'AMARELA'
        WHEN FAM.COD_RACA_COR_PESSOA = 4 THEN 'PARDA'
        WHEN FAM.COD_RACA_COR_PESSOA = 5 THEN 'INDIGENA'
        ELSE 'NAO INFORMADO'
    END AS RACA_COR,
    FAM.IND_DORMIR_RUA_MEMB,
    CASE
        WHEN FAM.COD_FAMILIA_INDIGENA_FAM = 1 THEN '1'
        WHEN FAM.COD_FAMILIA_INDIGENA_FAM = 2 THEN '0'
    END AS FAMILIA_INDIGENA,
    CASE
        WHEN FAM.IND_FAMILIA_QUILOMBOLA_FAM = 1 THEN '1'
        WHEN FAM.IND_FAMILIA_QUILOMBOLA_FAM = 2 THEN '0'
    END AS FAMILIA_QUILOMBOLA,
    NULL AS CS_ESPECIE,
    NULL AS CID,
    NULL AS DESCRICAO_CID,
    NULL AS TIPO_DESPACHO,
    NULL AS DT_DESPACHO,
    NULL AS DT_ENTRADA_REQUERIMENTO,
    NULL AS DT_INICIO_BENEFICIO,
    CASE    
        WHEN CAST(E.DT_ATUALIZACAO_FAM AS DATE) BETWEEN DT_EXTRACAO_DADOS_HDR - INTERVAL '2' YEAR AND DT_EXTRACAO_DADOS_HDR
             THEN 'ATUALIZADO'
        ELSE 'DESATUALIZADO'
    END AS SITUACAO_CAD_UNICO,
    B.PARTICIPACAO_CAMPANHA,
    FAM.DTA_ATUAL_MEMB,
    B.NU_MES_REF
FROM BASE_EXEMPLO_05.TABELA_EXEMPLO_072, ---------------------------referencia posterior
     VT_BEN_CAD B
JOIN BASE_EXEMPLO_07.TABELA_EXEMPLO_079 FAM ---------------------------referencia batimento
    ON B.CO_FAMILIAR_FAM = FAM.CO_FAMILIAR_FAM
   AND FAM.NU_MES_REF_MACICA = B.NU_MES_REF
LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_068 C
    ON TRIM
       (
           CAST(FAM.CO_MUNIC_IBGE_2_FAM AS CHAR(2)) ||
           LPAD(CAST(FAM.CO_MUNIC_IBGE_5_FAM AS VARCHAR(5)), 5, '0')
       ) = C.CO_IBGE7
LEFT JOIN BASE_EXEMPLO_05.TABELA_EXEMPLO_071 E ---------------------------referencia batimento
    ON FAM.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
WHERE COALESCE(TRIM(FAM.NUM_CPF_PESSOA), '') <> COALESCE(TRIM(B.NUM_CPF_PESSOA), '')
;

INSERT INTO BASE_EXEMPLO_01.TABELA_EXEMPLO_002
(
    TIPO_REGISTRO,
    NU_NB,
    CO_FAMILIAR_FAM,
    NU_CPF_T,
    NUM_CPF_PESSOA,
    CO_CHV_NATURAL_PESSOA,
    NU_NIS_T,
    NUM_NIS_PESSOA_ATUAL,
    NM_TIT_BENEF_T,
    NOM_PESSOA,
    DESC_PARENTESCO,
    FLAG_CADUNICO,
    FLAG_REF_MACICA_ANTERIOR,
    UF_MACICA,
    MUNICIPIO_MACICA,
    UF_CAD,
    MUNICIPIO_CAD,
    UF_AG_PGD,
    MUNICIPIO_AG_PGD,
    DT_NASC_T,
    DTA_NASC_PESSOA,
    IDADE_T,
    IDADE_PESSOA,
    NM_MAE_T,
    NOM_COMPLETO_MAE_PESSOA,
    GENERO,
    RACA_COR,
    IND_DORMIR_RUA_MEMB,
    FAMILIA_INDIGENA,
    FAMILIA_QUILOMBOLA,
    CS_ESPECIE,
    CID,
    DESCRICAO_CID,
    TIPO_DESPACHO,
    DT_DESPACHO,
    DT_ENTRADA_REQUERIMENTO,
    DT_INICIO_BENEFICIO,
    SITUACAO_CAD_UNICO,
    PARTICIPACAO_CAMPANHA,
    DTA_ATUAL_MEMB,
    NU_MES_REF
)
SELECT DISTINCT
    'NAO_CADASTRADO' AS TIPO_REGISTRO,
    A.NU_NB,
    NULL AS CO_FAMILIAR_FAM,
    A.NU_CPF_T,
    NULL AS NUM_CPF_PESSOA,
    NULL AS CO_CHV_NATURAL_PESSOA,
    A.ID_NIT_T AS NU_NIS_T,
    NULL AS NUM_NIS_PESSOA_ATUAL,
    A.NM_TIT_BENEF_T,
    NULL AS NOM_PESSOA,
    NULL AS DESC_PARENTESCO,
    '0' AS FLAG_CADUNICO,
    CASE
        WHEN M_ANT.NU_NB IS NOT NULL THEN '1' ELSE '0'
    END AS FLAG_REF_MACICA_ANTERIOR,
    A.NM_UF_MUN_T AS UF_MACICA,
    A.NM_MUN_T AS MUNICIPIO_MACICA,
    NULL AS UF_CAD,
    NULL AS MUNICIPIO_CAD,
    NULL AS UF_AG_PGD,
    NULL AS MUNICIPIO_AG_PGD,
    A.DT_NASC_T,
    NULL AS DTA_NASC_PESSOA,
    CAST
    (
        MONTHS_BETWEEN
        (
            LAST_DAY(CAST(CAST(A.NU_MES_REF AS CHAR(6)) || '01' AS DATE FORMAT 'YYYYMMDD')),
            A.DT_NASC_T
        ) / 12 AS INTEGER
    ) AS IDADE_T,
    NULL AS IDADE_PESSOA,
    A.NM_MAE_T,
    NULL AS NOM_COMPLETO_MAE_PESSOA,
    CASE 
        WHEN A.CS_SEXO_T = 1 THEN 'MASCULINO'
        WHEN A.CS_SEXO_T = 3 THEN 'FEMININO'
        ELSE 'NAO INFORMADO'
    END AS GENERO,
    'NAO INFORMADO' AS RACA_COR,
    NULL AS IND_DORMIR_RUA_MEMB,
    NULL AS FAMILIA_INDIGENA,
    NULL AS FAMILIA_QUILOMBOLA,
    A.CS_ESPECIE,
    A.CS_DIAG_1 AS CID,
    CASE 
        WHEN D.DS_DESCRICAO IS NOT NULL THEN D.DS_DESCRICAO
        WHEN D.DS_DESCRICAO IS NULL AND A.CS_ESPECIE <> 87 THEN 'NAO SE APLICA'
        ELSE 'NAO ENCONTRADO'
    END AS DESCRICAO_CID,
    CASE 
        WHEN A.CS_DESPACHO <> 4 THEN 'ADMINISTRATIVA'
        WHEN A.CS_DESPACHO = 4 THEN 'JUDICIAL'
    END AS TIPO_DESPACHO,
    A.D2_DDB AS DT_DESPACHO,
    A.D2_DER AS DT_ENTRADA_REQUERIMENTO,
    A.D2_DIB AS DT_INICIO_BENEFICIO,
    'NAO CADASTRADO' AS SITUACAO_CAD_UNICO,
    CASE 
        WHEN F.CAMPANHA IS NOT NULL THEN F.CAMPANHA
        ELSE 'NAO'
    END AS PARTICIPACAO_CAMPANHA,
    NULL AS DTA_ATUAL_MEMB,
    A.NU_MES_REF
FROM BASE_EXEMPLO_06.TABELA_EXEMPLO_073 A
LEFT JOIN
(
    SELECT DISTINCT
        NU_NB
    FROM BASE_EXEMPLO_06.TABELA_EXEMPLO_073
    WHERE CS_SIT_BENEF = 0
      AND CS_ESPECIE IN (11,12,18,30,40,60,87,88)
      AND CS_PA <> 3
      AND NU_MES_REF = 202506 ---------------------------referencia anterior
) M_ANT
    ON A.NU_NB = M_ANT.NU_NB
LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_069 D
    ON A.CS_DIAG_1 = D.CO_CID
LEFT JOIN VT_CAMPANHA F
    ON A.NU_NB = F.NUMERO_BENEFICIO
LEFT JOIN VT_BEN_CAD B
    ON A.NU_NB = B.NU_NB
WHERE A.CS_SIT_BENEF = 0
  AND A.CS_ESPECIE IN (11,12,18,30,40,60,87,88)
  AND A.CS_PA <> 3
  AND A.NU_MES_REF = 202507 ---------------------------referencia
  AND B.NU_NB IS NULL
;