MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_013
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/1'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_008
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/2'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_014
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/3'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_016
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/4'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_018
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/4'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_011
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2024/5'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_019
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/1'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_021
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/2'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_051
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/3'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_052
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/3B'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_053
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/4'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_054
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/5'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_055
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/6'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_056
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/7'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_057
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/8'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_058
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/9'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_039
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/10'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_040
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/11'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_041
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2025/12'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_042
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/1'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_043
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/2'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_044
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/3'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_045
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/4'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_047
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/5'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

MERGE INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
USING (
    SELECT NU_NB, SITUACAO_CADASTRAL_CAD, DT_ATUALIZACAO_FAM
    FROM (
        SELECT
            NU_NB,
            SITUACAO_CADASTRAL_CAD,
            DT_ATUALIZACAO_FAM,
            ROW_NUMBER() OVER (
                PARTITION BY NU_NB
                ORDER BY DT_ATUALIZACAO_FAM DESC
            ) AS RN
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_048
    ) sub
    WHERE sub.RN = 1
) AS src
ON BASE_EXEMPLO_02.TABELA_EXEMPLO_020.NUMERO_BENEFICIO = src.NU_NB
AND BASE_EXEMPLO_02.TABELA_EXEMPLO_020.CAMPANHA = '2026/6'
WHEN MATCHED THEN
    UPDATE SET
        SITUACAO_CADASTRAL_ATUAL_CADDIARIO = src.SITUACAO_CADASTRAL_CAD,
        ULTIMA_ATUALICAO_CADUNICO = src.DT_ATUALIZACAO_FAM;

-- ============================================================
-- Campanha 19 - 2026/7
-- Como esta campanha entra como nova lista no listão, removemos
-- antes a campanha do dia para evitar duplicidade em reprocessamento.
-- ============================================================

DELETE FROM BASE_EXEMPLO_02.TABELA_EXEMPLO_020
WHERE CAMPANHA = '2026/7';

INSERT INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
SELECT DISTINCT
    A.NU_NB AS NUMERO_BENEFICIO,
    A.NU_CPF_T,
    C.CS_ESPECIE,
    CASE
        WHEN D.QTDE_PESSOAS = 1 THEN '1'
        WHEN D.QTDE_PESSOAS > 1 THEN '+1'
        WHEN D.QTDE_PESSOAS IS NULL THEN 'NÃO INFORMADO'
    END AS UNIPESSOAL,
    CASE
        WHEN C.CS_DESPACHO = 4 THEN 'JUDICIAL'
        WHEN C.CS_DESPACHO <> 4 THEN 'ADMINISTRATIVO'
    END AS CONCESSAO,
    A.NO_MUNICIPIO,
    A.NO_SG_UF,
    A.SITUACAO_CADASTRAL_CAD,
    '2026/7' AS CAMPANHA,
    B.DT_ATUALIZACAO_FAM AS ULTIMA_ATUALICAO_CADUNICO,
    CASE
        WHEN B.SITUACAO_CADASTRAL_CAD IS NULL THEN 'NAO_CADASTRADO'
        ELSE B.SITUACAO_CADASTRAL_CAD
    END AS SITUACAO_CADASTRAL_ATUAL_CADDIARIO
FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_031 A
LEFT JOIN BASE_EXEMPLO_01.TABELA_EXEMPLO_049 B
    ON A.NU_NB = B.NU_NB
LEFT JOIN BASE_EXEMPLO_06.TABELA_EXEMPLO_073 C
    ON A.NU_NB = C.NU_NB
LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_074 D
    ON A.NU_NB = D.CO_NB
    AND D.NU_MES_REF_MACICA = C.NU_MES_REF
    AND D.IN_MARC_BPC = 1
WHERE C.CS_ESPECIE IN (87, 88)
    AND C.NU_MES_REF = 202606
    AND C.CS_SIT_BENEF = 0
    AND C.CS_PA <> 3;

-- ============================================================
-- Campanha 20 - 2026/8
-- Como esta campanha entra como nova lista no listão, removemos
-- antes a campanha do dia para evitar duplicidade em reprocessamento.
-- ============================================================

DELETE FROM BASE_EXEMPLO_02.TABELA_EXEMPLO_020
WHERE CAMPANHA = '2026/8';

INSERT INTO BASE_EXEMPLO_02.TABELA_EXEMPLO_020
SELECT DISTINCT
    A.NU_NB AS NUMERO_BENEFICIO,
    A.NU_CPF_T,
    C.CS_ESPECIE,
    CASE
        WHEN D.QTDE_PESSOAS = 1 THEN '1'
        WHEN D.QTDE_PESSOAS > 1 THEN '+1'
        WHEN D.QTDE_PESSOAS IS NULL THEN 'NÃO INFORMADO'
    END AS UNIPESSOAL,
    CASE
        WHEN C.CS_DESPACHO = 4 THEN 'JUDICIAL'
        WHEN C.CS_DESPACHO <> 4 THEN 'ADMINISTRATIVO'
    END AS CONCESSAO,
    A.NO_MUNICIPIO,
    A.NO_SG_UF,
    A.SITUACAO_CADASTRAL_CAD,
    '2026/8' AS CAMPANHA,
    B.DT_ATUALIZACAO_FAM AS ULTIMA_ATUALICAO_CADUNICO,
    CASE
        WHEN B.SITUACAO_CADASTRAL_CAD IS NULL THEN 'NAO_CADASTRADO'
        ELSE B.SITUACAO_CADASTRAL_CAD
    END AS SITUACAO_CADASTRAL_ATUAL_CADDIARIO
FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_032 A
LEFT JOIN BASE_EXEMPLO_01.TABELA_EXEMPLO_050 B
    ON A.NU_NB = B.NU_NB
LEFT JOIN BASE_EXEMPLO_06.TABELA_EXEMPLO_073 C
    ON A.NU_NB = C.NU_NB
LEFT JOIN BASE_EXEMPLO_08.TABELA_EXEMPLO_074 D
    ON A.NU_NB = D.CO_NB
    AND D.NU_MES_REF_MACICA = C.NU_MES_REF
    AND D.IN_MARC_BPC = 1
WHERE C.CS_ESPECIE IN (87, 88)
    AND C.NU_MES_REF = 202607
    AND C.CS_SIT_BENEF = 0
    AND C.CS_PA <> 3;