CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_013,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NUMERO_BENEFICIO AS NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NUMERO_BENEFICIO
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_012 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_008,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NUMERO_BENEFICIO AS NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NUMERO_BENEFICIO
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_007 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_014,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NUMERO_BENEFICIO AS NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NUMERO_BENEFICIO
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_009ÃO_INSCRITOS_COMPLETO_BLOQUEIO_VALIDADO_20241121 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_016,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NUMERO_BENEFICIO AS NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NUMERO_BENEFICIO
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_015 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_018,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NUMERO_BENEFICIO AS NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NUMERO_BENEFICIO
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_017 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_011,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.CPF_do_segurado,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_010 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_do_segurado = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_019,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_005 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_021,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_003 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_051,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_004 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_052,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.CPF_SEGURADO,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_006 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.CPF_SEGURADO = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_053,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_033 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_054,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_034 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_055,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_035 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_056,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_036 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_057,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_037 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_058,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_038 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_039,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_022 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_040,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_023 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_041,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_024 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_042,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_025 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_043,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT DISTINCT
        NU_NB,
        SITUACAO_CADASTRAL_CAD,
        DT_ATUALIZACAO_FAM
    FROM
    (
        SELECT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_026 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3, 5, 6)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_044,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_027 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_045,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_028 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_046,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_029 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_048,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_030 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_049,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_031 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);

CREATE MULTISET TABLE BASE_EXEMPLO_01.TABELA_EXEMPLO_050,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    BLOCKCOMPRESSION = ALWAYS,
    BLOCKCOMPRESSIONLEVEL = 9 AS
(
    SELECT *
    FROM
    (
        SELECT DISTINCT
            A.NU_NB,
            A.NU_CPF_T,
            E.DT_ATUALIZACAO_FAM,
            CASE
                WHEN C.NU_CPF_PESSOA IS NULL THEN 'NÃO CADASTRADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 24 THEN 'ATUALIZADO'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 24
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 36 THEN 'DESATUALIZADO_24_A_36'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 36
                     AND MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) <= 48 THEN 'DESATUALIZADO_36_A_48'
                WHEN MONTHS_BETWEEN(DT_EXTRACAO_DADOS, E.DT_ATUALIZACAO_FAM) > 48 THEN 'DESATUALIZADO_ACIMA_48'
            END AS SITUACAO_CADASTRAL_CAD,
            A.MOTIVO_EXPURGO,
            ROW_NUMBER() OVER (
                PARTITION BY A.NU_NB
                ORDER BY E.DT_ATUALIZACAO_FAM DESC NULLS LAST
            ) AS ORDEM
        FROM BASE_EXEMPLO_01.TABELA_EXEMPLO_032 A
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_070 C
            ON A.NU_CPF_T = C.NU_CPF_PESSOA
            AND C.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_075 D
            ON C.CO_CHV_NATURAL_PESSOA = D.CO_CHV_NATURAL_PESSOA
            AND D.IN_ULTIMO_REGISTRO = 1
            AND D.CO_EST_CADASTRAL_MEMB IN (3)
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_071 E
            ON C.CO_FAMILIAR_FAM = E.CO_FAMILIAR_FAM
            AND E.IN_ULTIMO_REGISTRO = 1
        LEFT JOIN BASE_EXEMPLO_03.TABELA_EXEMPLO_076 F
            ON C.CO_CHV_NATURAL_PREFEITURA = F.CO_CHV_NATURAL_PREFEITURA
            AND F.IN_ULTIMO_REGISTRO = 1
        WHERE A.MOTIVO_EXPURGO IS NULL
    ) BAT
    WHERE ORDEM = 1
)
WITH DATA
PRIMARY INDEX (NU_NB);